services:
  db:
    image: postgres
    container_name: postgres_db_container
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
      - TZ=Asia/Tokyo

  trading:
    build: .
    command: bash -c "python3 main_stream_usd.py"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
      - TZ=Asia/Tokyo

volumes:
  postgres_data: